Changed error names in JSON blocks to title case
osuosl/timesync pull request #71
Opened 2016-08-31 21:59 UTC by aaroncohen73

Changed all error names to title case to be consistent with the `Method Not Allowed` and `Bad Query Value` errors

2016-09-01 20:05 UTC, LyonesGamer commented
:+1:

2017-02-24 19:04 UTC, mathuin requested changes
I agree entirely that osuosl/timesync-node's src/errors.js and this file have to have the same information.  Let's consider the API to be the single source of truth -- set this however you think is right and ask for review from @LyonesGamer and maybe someone else, then make a PR for osuosl/timesync-node to make that one match this one, and we should be done with this issue.

2017-02-24 19:04 UTC, mathuin commented on source/errors.rst
> +    "error": "Object Not Found",
https://github.com/osuosl/timesync-node/blob/develop/src/errors.js#L33 shows `'Object not found'` is the correct form.

2017-02-24 19:04 UTC, mathuin commented on source/errors.rst
> +    "error": "Server Error",
https://github.com/osuosl/timesync-node/blob/develop/src/errors.js#L44-L46 shows `'Server error'` is the correct form.

2017-02-24 19:04 UTC, mathuin commented on source/errors.rst
> +    "error": "Invalid Foreign Key",
https://github.com/osuosl/timesync-node/blob/develop/src/errors.js#L58 shows `'Invalid foreign key'` is the correct form.

2017-02-24 19:04 UTC, mathuin commented on source/errors.rst
> +    "error": "Invalid Identifier",
https://github.com/osuosl/timesync-node/blob/develop/src/errors.js#L138 shows `'The provided identifier was invalid'` as the correct form.

2017-02-24 19:04 UTC, mathuin commented on source/errors.rst
> +    "error": "Invalid Username",
https://github.com/osuosl/timesync-node/blob/develop/src/errors.js#L138 shows `'Invalid username'` as the correct form.

2017-02-24 19:04 UTC, mathuin commented on source/errors.rst
> +    "error": "Authentication Failure",
https://github.com/osuosl/timesync-node/blob/develop/src/errors.js#L154 shows `'Authentication failure'` as the correct form.

2017-02-24 19:04 UTC, mathuin commented on source/errors.rst
> +    "error": "Slug Already Exists",
https://github.com/osuosl/timesync-node/blob/develop/src/errors.js#L169 shows `'The slug provided already exists'` as the correct form.

2017-02-24 19:04 UTC, mathuin commented on source/errors.rst
> +    "error": "Bad Object",
https://github.com/osuosl/timesync-node/blob/develop/src/errors.js#L112 shows `'Bad object'` as the correct form.

2017-02-24 19:04 UTC, mathuin commented on source/errors.rst
> +    "error": "Slugs Already Exist",
https://github.com/osuosl/timesync-node/blob/develop/src/errors.js#L169 shows the same string is used for single slugs that already exist and for multiple slugs that already exist.

2017-02-24 19:04 UTC, mathuin commented on source/errors.rst
> +    "error": "Username Already Exists",
https://github.com/osuosl/timesync-node/blob/develop/src/errors.js#L222 shows that `'Username already exists'` is the correct form.

2017-02-24 19:04 UTC, mathuin commented on source/errors.rst
> +    "text": "Username ${username} already exists",
The above line also shows that `'username ' + name + ' already exists'` is the correct form.

2017-02-24 20:50 UTC, mathuin approved these changes
I like it! All that's left is the possible change to the authentication failure description to match the server error. Otherwise, LGTM!

2017-02-24 20:50 UTC, mathuin commented on source/errors.rst
> +    "text": "${server_error}" // (e.g. exception text or sql error)
This is an excellent way to describe the diversity of potential strings.

2017-02-24 20:50 UTC, mathuin commented on source/errors.rst
>      "text": "Invalid username or password" / "Bad oAuth token" / etc
Do you want to do the same thing here you did with server error?  I think it would work well.

2017-02-27 18:32 UTC, mathuin commented
LGTM!  Do you need additional reviewers?

2017-02-27 18:34 UTC, aaroncohen73 commented
@LyonesGamer Could you give this PR another look before I merge it?

2017-03-01 20:22 UTC, MorganEPatch approved these changes

2017-03-01 20:26 UTC, merged