Organization Roles API Proposal
osuosl/timesync pull request #84
Opened 2017-03-01 21:46 UTC by LyonesGamer

Related to #83, #81.

This is my proposal for the API/Model structure for implementing database-backed arbitrary-string user roles, according to "solution 2" in #83.

2017-03-01 23:16 UTC, mathuin commented on source/users.rst
> +    "roles": ["intern"],
Why is this role `"intern"` and not `"Summer Intern"` like the others?

2017-03-01 23:17 UTC, mathuin commented on source/users.rst
> +    "roles": ["developer"],
Why is this role `"developer"` instead of `"Software Developer"` as below?

2017-03-01 23:27 UTC, LyonesGamer commented on source/users.rst
> +    "roles": ["intern"],
"A role consists...a machine-readable slug, which will be passed to all ``POST`` endpoints."

Maybe I should be clearer, but the idea is that when data is going from the client to the server, it uses slugs in order to ensure there are no errors in transmission and that the data is easily readable, and when data is going from the server to the client, it uses the actual names in order to allow the client to display them to the user and have them be human-readable. This is the same way the rest of our API works.

2017-03-01 23:41 UTC, mathuin commented on source/users.rst
> +    "roles": ["intern"],
If the API as written currently has the client sending the server slugs and the server sending the client names, then that's what should happen here.  I do wish I'd stepped in back when the API was first written to say that that sounds like a bad idea, but it's way too late for that now!

2017-03-01 23:57 UTC, mathuin commented on source/users.rst
> +    "roles": ["developer"],
This question was answered above.

2017-03-03 01:06 UTC, aaroncohen73 requested changes
I think that we should definitely include the role object in `model.rst` and give it other fields like `created_at`. However, whether it should inherit from the same common fields as times, projects, and activities or whether it should be a special snowflake like the user object is up for debate.

2017-03-03 01:06 UTC, aaroncohen73 commented on source/model.rst
I think that the Role object should be added to `model.rst` in order to be consistent with the other kinds of objects.

2017-03-03 01:06 UTC, aaroncohen73 commented on source/users.rst
> +    "roles": ["intern"],
I agree with @mathuin here that a list of role slugs should be returned instead of a list of human-readable names. ~~Since slugs are implied to be unique and names aren't, it would make it easier to write code to process them on the front end.~~ Either way it would potentially add another API call to match slugs to names or names to slugs. It just makes more sense to match based on a field with a unique value. This would also be consistent with the rest of the API, which sends arrays of slugs back to the client (i.e. the array of activity slugs returned with a time object).

EDIT: I read further and saw on line 426 that both slugs and names must be unique to each role. I still think that slugs should be returned instead of names, though, because they're used consistently throughout the rest of the API as references to objects.

2017-03-08 00:27 UTC, Kennric commented on source/users.rst
> +    "roles": ["intern"],
According to our documentation, when returning associated objects bundled with a main object (activities or projects for a time, for example) a list of slugs is returned. 

In practice, I believe the clients typically request all activities in a separate api call, and if needed, locally associate the display name of the activity from that data set, with its slug as listed in the time object. 

This kind of bundling essentially defines the user object as containing a field which is a list of role slugs - this is distinct from bundling associated objects (like revisions of times) where full objects are returned as children of the parent object.

2017-03-08 00:34 UTC, Kennric requested changes
This model should indeed be a first class model with the same standard fields as other objects.

Please re-name this model org-role or organization-role. 'role' implies a permission group, while this object only represents a role within the organization and has no bearing on permissions or associations within the API itself.

2017-03-08 22:53 UTC, LyonesGamer commented
Would maybe "group" be a better name? It's not implicitly limiting to just meaning position, but any arbitrary group, and it has no implications of permissions or authorization.

2017-03-16 21:38 UTC, Kennric commented
@LyonesGamer 'user_role' has the same issue as just 'role'.

2017-04-12 18:05 UTC, LyonesGamer commented
@Kennric I agree that `user_role` would, but what about `user group`?

2017-05-03 18:09 UTC, Kennric commented
@LyonesGamer I still think user_group evokes application level groups and permissions, it needs to be something not immediately associated with that. I still think organization role is better, but not ideal, and I haven't found a better word.

I also foresee a future feature in which a user can have a particular role within a project, for instance a student developer might be doing strictly graphic design on a particular project, which may be billed differently. We'll want  a similar distinct taxonomy for those cases as well.

2017-06-30 18:28 UTC, Kennric approved these changes

2017-06-30 20:55 UTC, alxngyn approved these changes
proposal ++

2017-11-10 20:01 UTC, merged